# Application Configuration
app:
  name: "Try This AI Video Generator"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# API Configuration
api:
  openai:
    model: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.7
    timeout: 30  # seconds

  elevenlabs:
    model: "eleven_monolingual_v1"
    stability: 0.5
    similarity_boost: 0.75
    timeout: 30  # seconds

# Video Generation Settings
video:
  resolution:
    width: 1920
    height: 1080
  fps: 30
  codec: "libx264"
  bitrate: "5000k"
  audio:
    bitrate: "192k"
    sample_rate: 44100
    channels: 2

# File Management
files:
  directories:
    scripts: "scripts"
    audio: "audio"
    video: "video"
    thumbnails: "thumbnails"
  max_size:
    script: 1048576  # 1MB
    image: 5242880  # 5MB
    audio: 10485760  # 10MB
  allowed_extensions:
    scripts: [".md", ".txt"]
    images: [".png", ".jpg", ".jpeg"]
    audio: [".mp3", ".wav"]

# YouTube Integration
youtube:
  upload:
    privacy: "private"
    category: "22"  # People & Blogs
    default_language: "en"
  metadata:
    max_title_length: 100
    max_description_length: 5000
    max_tags: 500

# Testing Configuration
testing:
  test_data:
    script_length: 500
    max_duration: 60  # seconds
  coverage:
    minimum: 80
    exclude:
      - "tests/*"
      - "__pycache__/*"
      - ".venv/*"

# Logging Configuration
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Environment Configuration
environment:
  python:
    version: "3.9.13"
    virtualenv:
      path: ".venv"
      requirements:
        - "requirements.txt"
        - "requirements-dev.txt"
  paths:
    virtualenv: ".venv"
    python_executable: ".venv/Scripts/python.exe"  # Windows path
    # python_executable: ".venv/bin/python"  # Unix path
